### ISSUE TITLE
Before match issues

### ISSUE THREAD

**Issue by TheGalaxyLord** [ImagicalGamer/SurvivalGamesV2#2]
So before the match starts when it counts down the players can hit each other and even after the match starts you can still hit the player and there is also a chance that you will spawn on players.

**Comment by ImagicalGamer** [comment]
That is a known bug, currently working on a fix. There is no grace period so thats why you can damage players at the beginning of a match. If your running the plugin on ImagicalMine that's why it will spawn players on top of each other.

**Comment by ImagicalGamer** [comment]
Easy fix for players hitting each other, spawn positions 4-5 blocks apart.
