### ISSUE TITLE
on end game clear all() error

### ISSUE THREAD

**Issue by Driesboy** [ImagicalGamer/SurvivalGamesV2#5]

**Comment by ImagicalGamer** [comment]
Crash dump or error log please.

**Comment by Driesboy** [comment]
No dump but error in console

**Comment by ImagicalGamer** [comment]
What's the error? I can't seem to re-create this. I'm not using PHP7 Genisys when testing this btw.

**Comment by ImagicalGamer** [comment]
Tested on Genisys PHP7 no issue when I tested it

**Comment by ImagicalGamer** [comment]
Issue should be fixed if your using the latest Genisys build.
