### ISSUE TITLE
use this https://github.com/Driesboy/SurvivalGames/commit/556f2b68f07e2d49ab4be34062a32932b8425866

### ISSUE THREAD

**Issue by Driesboy** [ImagicalGamer/SurvivalGamesV2#8]
https://github.com/Driesboy/SurvivalGames/commit/556f2b68f07e2d49ab4be34062a32932b8425866

**Comment by Driesboy** [comment]
fixing genisys

**Comment by ImagicalGamer** [comment]
Have you tested it? I'll test it on ImagicalMine and PocketMine if it works you can make a pull request and I'll make it another branch or merge them.

**Comment by ImagicalGamer** [comment]
I tested it on Genisys and ImagicalMine most of it worked. There were a few bugs and errors within the code. Thanks for the Genisys fix!
